version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.10.2
    environment:
      PYTHONPATH: /app
    matrix:
      os:
        - x86-macos
        - arm-macos
        - linux
        - windows
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run build script
          command: python scripts/build_app.py

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
