on:
  push:
    branches:
    - "main"
    #tags:
    #- '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "windows-latest"]

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: 3.10.7
    - run: pip install -r requirements.txt
    - run: pip install -r requirements_build.txt
    - run: pip install --no-dependencies -e .
    - run: python scripts/pack_app.py
    # Optionally verify that it works (provided that it does not need user interaction)
    #- run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@main
      with:
        name: Tuttle-${{ github.sha }}-${{ matrix.os }}
        path: dist/
