on:
  push:
    branches:
    - "main"
    #tags:
    #- '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: get-tag
      run: |
        echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.7
    - run: pip install -r requirements.txt
    - run: pip install -r requirements_dev.txt
    - run: python scripts/build_app.py
    # Optionally verify that it works (provided that it does not need user interaction)
    #- run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v3
      with:
        name: Tuttle-${{ steps.get-tag.output }}-${{ matrix.os }}
        path: dist/
